CREATE TABLE C2G_REQUEST_LOG 
(
	ID			NUMBER,
	URL			VARCHAR2(1024),
	SVN_URL		VARCHAR2(512),
	SQL_STMTS	CLOB,
	SQL_COUNT	NUMBER,
	REQUEST_START TIMESTAMP,
	REQUEST_MS	NUMBER,
	DB_MS		NUMBER,
	PRIMARY KEY (ID)
);

CREATE SEQUENCE C2G_REQUEST_LOG_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER C2G_REQUEST_LOG_INS 
BEFORE INSERT
ON C2G_REQUEST_LOG FOR EACH ROW
BEGIN
  SELECT C2G_REQUEST_LOG_SEQ.nextval INTO :new.ID FROM DUAL;
END; 
/
