-- 
-- Achtung: Wegen eines Bugs in Liferay werden VARCHAR-Felder existierender Tabellen auf 1/4tel Länge gekürzt.
-- Daher sollte dieses Script erst nach dem ersten Liferay-Start ausgeführt werden. 
--

-- Tabelle für Konfigurationen
CREATE TABLE ADM_CONFIG
(
	ID number, 
	PORTLET_ID VARCHAR2(255) NOT NULL,
	COMMUNITY_ID INT NOT NULL,
	CONFIG_NAME VARCHAR2(255) NOT NULL,
	CONFIG_XML BLOB NOT NULL,
	USER_CREATED VARCHAR2(255) NOT NULL,
	DATE_CREATED TIMESTAMP NOT NULL,
	DATE_UPDATED TIMESTAMP DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (ID)
);

CREATE sequence ADM_CONFIG_SEQ start WITH 1 increment BY 1 nomaxvalue;

CREATE OR REPLACE TRIGGER TRG_ADM_CONFIG_INS 
BEFORE INSERT
ON ADM_CONFIG FOR EACH ROW
BEGIN
  SELECT ADM_CONFIG_SEQ.nextval INTO :new.ID FROM DUAL;
END; 
/

create or replace trigger TRG_ADM_CONFIG_UPD
before update
on ADM_CONFIG for each row
begin
	select CURRENT_TIMESTAMP into :new.DATE_UPDATED from dual;
end;
/

-- Tabelle für Berechtigungen
CREATE TABLE RESOURCEID_PRIMKEY 
(
  PRIMKEY NUMBER NOT NULL PRIMARY KEY,
  RESOURCEID VARCHAR2(100) NOT NULL UNIQUE
);

CREATE SEQUENCE RESOURCEID_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE TABLE C2G_REQUEST_LOG 
(
	ID			NUMBER,
	URL			VARCHAR2(1024),
	SVN_URL		VARCHAR2(512),
	SQL_STMTS	CLOB,
	SQL_COUNT	NUMBER,
	REQUEST_START TIMESTAMP,
	REQUEST_MS	NUMBER,
	DB_MS		NUMBER,
	PRIMARY KEY (ID)
);

CREATE SEQUENCE C2G_REQUEST_LOG_SEQ INCREMENT BY 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE OR REPLACE TRIGGER C2G_REQUEST_LOG_INS 
BEFORE INSERT
ON C2G_REQUEST_LOG FOR EACH ROW
BEGIN
  SELECT C2G_REQUEST_LOG_SEQ.nextval INTO :new.ID FROM DUAL;
END; 
/

