
CREATE TABLE DBWEB_USERS
(
  USERNAME   VARCHAR(15) 				NOT NULL,
  PASSWORD   VARCHAR(80)                NOT NULL,
  VORNAME    VARCHAR(128),
  NAME       VARCHAR(128),
  ABTEILUNG  VARCHAR(128),
  TELEFON    VARCHAR(128),
  EMAIL      VARCHAR(128),
  PRIMARY KEY (USERNAME)
 );

CREATE TABLE DBWEB_ROLES
(
  USERNAME  VARCHAR(255)                  NOT NULL,
  ROLENAME  VARCHAR(255)                  NOT NULL,
  PRIMARY KEY (USERNAME, ROLENAME)
);


INSERT INTO DBWEB_USERS (USERNAME, PASSWORD, VORNAME, NAME, ABTEILUNG, TELEFON, EMAIL) VALUES ('carsten', 'eai', 'Carsten', 'Mjartan', 'CC', '+49 212 233628-64', 'carsten.mjartan@union-investment.de');
INSERT INTO DBWEB_USERS (USERNAME, PASSWORD, VORNAME, NAME, ABTEILUNG, TELEFON, EMAIL) VALUES ('dirk', 'eai', 'Dirk', 'Eisold', 'CC', '+49 212 233628-123', 'dirk.eisold@union-investment.de');

INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('carsten', 'portlet-crud-r');
INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('carsten', 'portlet-crud-w');
INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('carsten', 'portlet-crud-u');
INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('carsten', 'portlet-crud-d');

INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('dirk', 'portlet-crud-r');
INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('dirk', 'portlet-crud-w');
INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('dirk', 'portlet-crud-u');
INSERT INTO DBWEB_ROLES (USERNAME, ROLENAME) VALUES ('dirk', 'portlet-crud-d');
