-- 
-- Achtung: Wegen eines Bugs in Liferay werden VARCHAR-Felder existierender Tabellen auf 1/4tel Länge gekürzt.
-- Daher sollte dieses Script erst nach dem ersten Liferay-Start ausgeführt werden. 
--

-- Tabelle für Konfigurationen
CREATE TABLE ADM_CONFIG
(
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	PORTLET_ID VARCHAR(255) NOT NULL,
	COMMUNITY_ID INT NOT NULL,
	CONFIG_NAME VARCHAR(255) NOT NULL,
	CONFIG_XML BLOB NOT NULL,
	USER_CREATED VARCHAR(255) NOT NULL,
	DATE_CREATED DATETIME NOT NULL,
	DATE_UPDATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TRIGGER `SET_DATE_CREATED` BEFORE INSERT ON  `ADM_CONFIG` 
FOR EACH ROW 
SET NEW.DATE_CREATED = NOW();

-- Tabelle für Berechtigungen
CREATE TABLE RESOURCEID_PRIMKEY 
(
  PRIMKEY BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  RESOURCEID VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE C2G_REQUEST_LOG 
(
	ID			INT AUTO_INCREMENT PRIMARY KEY,
	URL			VARCHAR(1024),
	SVN_URL		VARCHAR(512),
	SQL_STMTS	TEXT,
	SQL_COUNT	INT,
	REQUEST_START DATETIME,
	REQUEST_MS	INT,
	DB_MS		INT
);

