DROP FUNCTION FUNC_SLEEP;

DROP TABLE TEST_NAME;
DROP TABLE T;
DROP TABLE TEST_CRUD2;
DROP TABLE TEST_CRUD2_DROP_NUMBER;
DROP TABLE TEST_CRUD2_DROP_DATE;
DROP TABLE TEST_CRUD2_DROP_TEXT;

DROP TABLE TEST_CHILD;
DROP TABLE TEST_PARENT;
DROP TABLE TEST_CLOB;
DROP TABLE TEST_BLOB;
